In [1]:
import sys
sys.path.append("..")
import numpy as np
import matplotlib.pyplot as plt
import math
from src.gradient import *
from src.logistic import *
from src.loss import *
from src.helpers import *
from implementations import *
import matplotlib.pyplot as plt
#from implementations_v2 import *
#from src import *

import datetime

In [2]:
y_train, tx_train, ids_train, y_test, tx_test, ids_test =load("train.csv","test.csv")
print("Y:")
print(y_train)
print("input:")
print(tx_train)
print("ids:")
print(ids_train)

num_samples = tx_train.shape[0]
num_features = tx_train.shape[1]




Loading the raw training and test set data...

... finished.
Y:
[ 1. -1. -1. ...  1. -1. -1.]
input:
[[ 138.47    51.655   97.827 ...    1.24    -2.475  113.497]
 [ 160.937   68.768  103.235 ... -999.    -999.      46.226]
 [-999.     162.172  125.953 ... -999.    -999.      44.251]
 ...
 [ 105.457   60.526   75.839 ... -999.    -999.      41.992]
 [  94.951   19.362   68.812 ... -999.    -999.       0.   ]
 [-999.      72.756   70.831 ... -999.    -999.       0.   ]]
ids:
[100000 100001 100002 ... 349997 349998 349999]


In [3]:
print('Total size:', num_samples)
print('Feature size:', num_features)

Total size: 250000
Feature size: 30


In [4]:
error_value = -999.0

# Cleaned input array by replacing errors with most frequent values
x_clean_mf = clean_data(tx_train, error_value, most_frequent)

# Cleaned input array by replacing errors with mean
x_clean_mean = clean_data(tx_train, error_value, np.mean)

# Cleaned input array by replacing errors with median
x_clean_median = clean_data(tx_train, error_value, np.median)

In [5]:
x_clean = x_clean_median
# Normalised version of the data (without the 1's column)
x_normal = normalize(x_clean)
x_normal.shape

(250000, 30)

In [6]:
first_col = np.ones((num_samples, 1))
tx = np.concatenate((first_col, x_normal), axis=1)
tx.shape

(250000, 31)

In [16]:
LS_losses, LS_ws =  least_squares(y_train,tx)


In [17]:
print(LS_losses)
print(LS_ws)


0.33995813229841937
[ 2.67925739e+02  2.04981152e-02 -6.34475618e-01 -5.71807284e-01
  1.79919435e-02  1.80206040e+00  4.11457885e-02  3.24891081e-01
  3.17174394e+01 -1.10448281e-01 -2.45596829e+02 -1.96874617e+01
  8.92048817e+00  3.07774884e+01  2.46325887e+02 -5.84122887e-02
 -3.95839297e-02  2.46751271e+02 -4.56843478e-02  1.24774625e-01
  2.70438863e-01  4.61271985e-02 -3.35153821e-02  4.95676584e+00
 -6.89936132e-02  3.74676193e-02  1.57114058e-02 -9.07059641e-02
  1.22761438e-01 -1.46240355e-01  2.45555779e+02]


In [21]:
lambda_=1
ridge_ws, ridge_losses =  ridge_regression(y_train,tx,lambda_)

print(ridge_losses)
print(ridge_ws)

0.431388452628382
[-0.04727118 -0.02611867 -0.06066865 -0.01624189  0.03886474  0.02262539
  0.02857887  0.02206788  0.02205427  0.0097985   0.00196522  0.02150685
  0.02464882  0.02301246  0.02822324  0.02309389  0.02305318 -0.00500778
  0.02311167  0.02311188 -0.00017527  0.02316281 -0.02451294  0.02304974
 -0.0015702   0.02309671  0.02311475 -0.00511525  0.02310706  0.02308164
  0.02494526]


In [8]:
max_iter_v2 = 50
gamma_v2 = 0.08


# Initialization
w_initial = np.ones((31,))

LR_SGD_losses, LR_SGD_ws =  mean_squared_error_sgd(y_train,tx,w_initial,max_iter_v2,gamma_v2)

SGD(0/49): loss=23.313976402092806, w0=0.6429208350442686, w1=0.44580974038197607
SGD(1/49): loss=21.306045663073746, w0=1.3088699513040263, w1=0.6802726855976166
SGD(2/49): loss=23.93840496637648, w0=0.909185217976026, w1=0.31872685424521097
SGD(3/49): loss=24.446699935029816, w0=1.2184031095205732, w1=0.5598728525623662
SGD(4/49): loss=12.140480504418747, w0=1.4840783837327904, w1=1.249440183884788
SGD(5/49): loss=16.377397932677628, w0=1.2607708183702129, w1=1.0150039569802547
SGD(6/49): loss=8.819323360921986, w0=1.30180686679452, w1=1.0470062412427907
SGD(7/49): loss=9.434108362542798, w0=1.3886178378581988, w1=1.1147064579976051
SGD(8/49): loss=11.927385246745036, w0=1.5527136059505016, w1=1.2647159725938224
SGD(9/49): loss=20.079296410466043, w0=1.6007103344969, w1=1.3052490764865738
SGD(10/49): loss=24.80585515985798, w0=1.1238812686191457, w1=0.21200196766430923
SGD(11/49): loss=11.09244313240809, w0=1.5400279776341737, w1=0.6939564005941565
SGD(12/49): loss=20.770148761814973

In [9]:
max_iter_v2 = 200
gamma_v2 = 0.06

# Initialization
w_initial = np.ones((31,))

LS_ws, LS_losses = logistic_regression(y_train,tx,w_initial,max_iter_v2,gamma_v2)


Current iteration of GD=0, loss=23.31397640209284
Current iteration of GD=1, loss=12.166022286279382
Current iteration of GD=2, loss=11.532553467455816
Current iteration of GD=3, loss=11.002015741325307
Current iteration of GD=4, loss=10.54961528438139
Current iteration of GD=5, loss=10.156928198271192
Current iteration of GD=6, loss=9.810249677878767
Current iteration of GD=7, loss=9.499371520227994
Current iteration of GD=8, loss=9.216676813600193
Current iteration of GD=9, loss=8.956469494811046
Current iteration of GD=10, loss=8.714477824270205
Current iteration of GD=11, loss=8.48748664630522
Current iteration of GD=12, loss=8.27306501501767
Current iteration of GD=13, loss=8.069364438976889
Current iteration of GD=14, loss=7.874969420270411
Current iteration of GD=15, loss=7.68878671893458
Current iteration of GD=16, loss=7.509963295133544
Current iteration of GD=17, loss=7.337825488936329
Current iteration of GD=18, loss=7.171833928338649
Current iteration of GD=19, loss=7.01155

KeyboardInterrupt: 

In [ ]:
plt.plot(LS_losses)

In [ ]:
max_iter_v2 = 400
gamma_v2 = 0.01

# Initialization
w_initial = np.ones((31,))

LR_GD_losses, LR_GD_ws =  mean_squared_error_gd(y_train,tx,w_initial,max_iter_v2,gamma_v2)


In [ ]:
plt.plot(LR_GD_losses)